name: Build Docker image and publish to ACR

on:
  push:
    branches:
      - master

env:
  ACR_REPO: ${{vars.ACR_NAME}}.azurecr.io

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven
      - name: Build docker image
        run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ env.ACR_REPO }}/spring-petclinic:${{ github.sha }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_REPO}}
          username: ${{ secrets.AZURE_USER }}
          password: ${{ secrets.AZURE_PASSWORD }}

      - name: Push Docker Image to ACR
        run: docker push ${{ env.ACR_REPO }}/spring-petclinic:${{ github.sha }}

      - name: Deploy to Azure AppService
        uses: azure/webapps-deploy@v2
        with:
          app-name: sping-petclinic
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          images: '${{ env.ACR_NAME }}/spring-petclinic:${{ github.sha }}'
